-- MySQL Script generated by MySQL Workbench
-- Tue Jun  1 21:10:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project` (
  `project_id` VARCHAR(45) NOT NULL,
  `project_name` INT NOT NULL,
  `cantdadUsuarios` INT NOT NULL,
  `project_manager` VARCHAR(45) NOT NULL,
  `project_start_date` FLOAT NOT NULL,
  `project_end_date` VARCHAR(45) NULL,
  `project_priority` TINYINT NULL,
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`calendar` (
  `calendar_id` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `moth` INT NOT NULL,
  `day` INT NOT NULL,
  `minutes` FLOAT NOT NULL,
  `houres` FLOAT NOT NULL,
  PRIMARY KEY (`calendar_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` VARCHAR(45) NOT NULL,
  `_user_name` VARCHAR(45) NOT NULL,
  `user_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grafica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gantt_chart` (
  `gantt_chart_id` VARCHAR(45) NOT NULL,
  `gantt_chart_period` FLOAT NOT NULL,
  PRIMARY KEY (`gantt_chart_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`task` (
  `task_id` VARCHAR(45) NOT NULL,
  `task_start_date` FLOAT NOT NULL,
  `task_end_date` FLOAT NOT NULL,
  `task_name` VARCHAR(45) NOT NULL,
  `task_state` INT NULL,
  `task_state_type` VARCHAR(45) NULL,
  `task_assigned_user` VARCHAR(45) NULL,
  `task_priority` TINYINT NULL,
  PRIMARY KEY (`task_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_has_tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_task` (
  `user_user_id` VARCHAR(45) NOT NULL,
  `task_task_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_user_id`, `task_task_id`),
  CONSTRAINT `fk_user_has_task_user`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_task_task1`
    FOREIGN KEY (`task_task_id`)
    REFERENCES `mydb`.`task` (`task_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_has_tarea_tarea1_idx` ON `mydb`.`usuario_has_tarea` (`tarea_IDtarea` ASC) VISIBLE;

CREATE INDEX `fk_usuario_has_tarea_usuario_idx` ON `mydb`.`usuario_has_tarea` (`usuario_IDusuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_has_Calendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_has_Calendario` (
  `usuario_IDusuario` VARCHAR(45) NOT NULL,
  `Calendario_IDcalendario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario_IDusuario`, `Calendario_IDcalendario`),
  CONSTRAINT `fk_usuario_has_Calendario_usuario1`
    FOREIGN KEY (`usuario_IDusuario`)
    REFERENCES `mydb`.`usuario` (`IDusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_Calendario_Calendario1`
    FOREIGN KEY (`Calendario_IDcalendario`)
    REFERENCES `mydb`.`Calendario` (`IDcalendario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_has_Calendario_Calendario1_idx` ON `mydb`.`usuario_has_Calendario` (`Calendario_IDcalendario` ASC) VISIBLE;

CREATE INDEX `fk_usuario_has_Calendario_usuario1_idx` ON `mydb`.`usuario_has_Calendario` (`usuario_IDusuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_has_Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_has_Proyecto` (
  `usuario_IDusuario` VARCHAR(45) NOT NULL,
  `Proyecto_IDproyecto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario_IDusuario`, `Proyecto_IDproyecto`),
  CONSTRAINT `fk_usuario_has_Proyecto_usuario1`
    FOREIGN KEY (`usuario_IDusuario`)
    REFERENCES `mydb`.`usuario` (`IDusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_Proyecto_Proyecto1`
    FOREIGN KEY (`Proyecto_IDproyecto`)
    REFERENCES `mydb`.`Proyecto` (`IDproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_has_Proyecto_Proyecto1_idx` ON `mydb`.`usuario_has_Proyecto` (`Proyecto_IDproyecto` ASC) VISIBLE;

CREATE INDEX `fk_usuario_has_Proyecto_usuario1_idx` ON `mydb`.`usuario_has_Proyecto` (`usuario_IDusuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_has_Calendario_has_Grafica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_has_Calendario_has_Grafica` (
  `usuario_has_Calendario_usuario_IDusuario` VARCHAR(45) NOT NULL,
  `usuario_has_Calendario_Calendario_IDcalendario` VARCHAR(45) NOT NULL,
  `Grafica_IDgrafica` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario_has_Calendario_usuario_IDusuario`, `usuario_has_Calendario_Calendario_IDcalendario`, `Grafica_IDgrafica`),
  CONSTRAINT `fk_usuario_has_Calendario_has_Grafica_usuario_has_Calendario1`
    FOREIGN KEY (`usuario_has_Calendario_usuario_IDusuario` , `usuario_has_Calendario_Calendario_IDcalendario`)
    REFERENCES `mydb`.`usuario_has_Calendario` (`usuario_IDusuario` , `Calendario_IDcalendario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_Calendario_has_Grafica_Grafica1`
    FOREIGN KEY (`Grafica_IDgrafica`)
    REFERENCES `mydb`.`Grafica` (`IDgrafica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_has_Calendario_has_Grafica_Grafica1_idx` ON `mydb`.`usuario_has_Calendario_has_Grafica` (`Grafica_IDgrafica` ASC) VISIBLE;

CREATE INDEX `fk_usuario_has_Calendario_has_Grafica_usuario_has_Calendari_idx` ON `mydb`.`usuario_has_Calendario_has_Grafica` (`usuario_has_Calendario_usuario_IDusuario` ASC, `usuario_has_Calendario_Calendario_IDcalendario` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
