/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author braul
 */
public class InterfazCrearProyect extends javax.swing.JFrame {

    /**
     * Creates new form InterfazCrearProyect
     */
    public InterfazCrearProyect() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombreProyecto = new javax.swing.JTextField();
        jTextFieldFecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNotas = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButtonCrearProyecto = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del proyecto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de inicio:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jTextFieldNombreProyecto.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldNombreProyecto.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextFieldNombreProyecto.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldNombreProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 400, -1));

        jTextFieldFecha.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldFecha.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextFieldFecha.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 400, -1));

        jTextAreaNotas.setBackground(new java.awt.Color(51, 51, 51));
        jTextAreaNotas.setColumns(20);
        jTextAreaNotas.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextAreaNotas.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaNotas.setRows(5);
        jScrollPane1.setViewportView(jTextAreaNotas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 580, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Notas:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jButtonCrearProyecto.setBackground(new java.awt.Color(51, 51, 51));
        jButtonCrearProyecto.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButtonCrearProyecto.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCrearProyecto.setText("Crear");
        jButtonCrearProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearProyectoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCrearProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 665, 366));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearProyectoActionPerformed
        // TODO add your handling code here:
        int validacion = 0;
        String nombre_proyecto, fecha, notas;
        nombre_proyecto = jTextFieldNombreProyecto.getText().trim();
        fecha = jTextFieldFecha.getText().trim();
        notas = jTextAreaNotas.getText().trim();
        
        if(nombre_proyecto.equals("")){
            jTextFieldNombreProyecto.setBackground(Color.red);
            validacion++;
        }
        
        if(fecha.equals("")){
            jTextFieldFecha.setBackground(Color.red);
            validacion++;
        }
        
        if(notas.equals("")){
            jTextAreaNotas.setBackground(Color.red);
            validacion++;
        }
        
        
        try{
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select nombre_proyecto from proyecto where nombre_proyecto = '"
                    +nombre_proyecto+ "'");
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                jTextFieldNombreProyecto.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Nombre de proyecto no disponible.");
                cn.close();
            } else{
                cn.close();
                if (validacion==0) {
                    try{
                        Connection cn2 = Conexion.conectar();
                        PreparedStatement pst2 = cn2.prepareStatement("insert into proyecto values(?,?,?,?)");
                        pst2.setInt(1, 0);
                        pst2.setString(2, nombre_proyecto);
                        pst2.setString(3, fecha);
                        pst2.setString(4, notas);
                        pst2.executeUpdate();
                        cn2.close();
                        limpiar();
                        jTextFieldNombreProyecto.setBackground(Color.GREEN);
                        jTextFieldFecha.setBackground(Color.GREEN);
                        jTextAreaNotas.setBackground(Color.GREEN);
                        JOptionPane.showMessageDialog(null, "Proyecto creado con exito.");
                        InterfazInicial abrir = new InterfazInicial();
                        abrir.setVisible(true);
                        dispose();
                        this.dispose();
                        
                    }catch(Exception e){
                        System.err.println("Error en crear proyecto.");
                        JOptionPane.showMessageDialog(null, "Error en el sistema al crear proyecto.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos.");
                }
            }
        }catch(Exception e){
            System.err.println("Error en validar proyecto.");
            JOptionPane.showMessageDialog(null, "Error al comparar proyecto.");
        }
//        InterfazInicial abrir = new InterfazInicial();
//        abrir.setVisible(true);
//        dispose();
    }//GEN-LAST:event_jButtonCrearProyectoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        InterfazSelecProyect abrir = new InterfazSelecProyect();
        abrir.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCrearProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCrearProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCrearProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCrearProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCrearProyect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCrearProyecto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaNotas;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldNombreProyecto;
    // End of variables declaration//GEN-END:variables
public void limpiar(){
    jTextFieldNombreProyecto.setText("");
    jTextFieldFecha.setText("");
    jTextAreaNotas.setText("");
}
}
