/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author braul
 */
public class InterfazSelecProyect extends javax.swing.JFrame {

    /**
     * Creates new form InterfazSelecProyect
     */
    public InterfazSelecProyect() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNuevoProyecto = new javax.swing.JButton();
        jButtonAbrirProy = new javax.swing.JButton();
        jButtonBorrarProy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNuevoProyecto.setBackground(new java.awt.Color(51, 51, 51));
        jButtonNuevoProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/project_crear.png"))); // NOI18N
        jButtonNuevoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoProyectoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNuevoProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jButtonAbrirProy.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAbrirProy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/project_abrir.png"))); // NOI18N
        jButtonAbrirProy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirProyActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAbrirProy, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jButtonBorrarProy.setBackground(new java.awt.Color(51, 51, 51));
        jButtonBorrarProy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/project_borrar.png"))); // NOI18N
        jButtonBorrarProy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarProyActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBorrarProy, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 302));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoProyectoActionPerformed
        // TODO add your handling code here:
        InterfazCrearProyect abrir = new InterfazCrearProyect();
        abrir.setVisible(true);
        String texto="Crear Proyecto";
        jButtonNuevoProyecto.setToolTipText(texto);
        dispose();
    }//GEN-LAST:event_jButtonNuevoProyectoActionPerformed

    private void jButtonAbrirProyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirProyActionPerformed
        // TODO add your handling code here:
        InterfazAbrirProyecto abrir = new InterfazAbrirProyecto();
        abrir.setVisible(true);
        String texto="Abrir Proyecto";
        jButtonNuevoProyecto.setToolTipText(texto);
        dispose();
    }//GEN-LAST:event_jButtonAbrirProyActionPerformed

    private void jButtonBorrarProyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarProyActionPerformed
        // TODO add your handling code here:
        InterfazEliminarProyecto abrir = new InterfazEliminarProyecto();
        abrir.setVisible(true);
        String texto="Borrar Proyecto";
        jButtonNuevoProyecto.setToolTipText(texto);
        dispose();
    }//GEN-LAST:event_jButtonBorrarProyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazSelecProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazSelecProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazSelecProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazSelecProyect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazSelecProyect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrirProy;
    private javax.swing.JButton jButtonBorrarProy;
    private javax.swing.JButton jButtonNuevoProyecto;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
