/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author braul
 */
public class InterfazTarea extends javax.swing.JFrame {

    /**
     * Creates new form InterfazTarea
     */
    public InterfazTarea() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonBaja = new javax.swing.JRadioButton();
        jRadioButtonMedia = new javax.swing.JRadioButton();
        jRadioButtonAlta = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTarea = new javax.swing.JTextField();
        jTextFieldFechaInicio = new javax.swing.JTextField();
        jTextFieldFechaFin = new javax.swing.JTextField();
        jTextFieldResponsable = new javax.swing.JTextField();
        jButtonSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNotas = new javax.swing.JTextArea();
        jButtonAgregarTarea = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tarea:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha inicio:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha final:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Responsable:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Prioridad:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jRadioButtonBaja.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jRadioButtonBaja.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonBaja.setText("Baja");
        getContentPane().add(jRadioButtonBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jRadioButtonMedia.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jRadioButtonMedia.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonMedia.setText("Media");
        getContentPane().add(jRadioButtonMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        jRadioButtonAlta.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jRadioButtonAlta.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonAlta.setText("Alta");
        getContentPane().add(jRadioButtonAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Notas:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jTextFieldTarea.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldTarea.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextFieldTarea.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 600, -1));

        jTextFieldFechaInicio.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldFechaInicio.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextFieldFechaInicio.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 600, -1));

        jTextFieldFechaFin.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldFechaFin.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextFieldFechaFin.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 600, -1));

        jTextFieldResponsable.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldResponsable.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextFieldResponsable.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 600, -1));

        jButtonSalir.setBackground(new java.awt.Color(51, 51, 51));
        jButtonSalir.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("x");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        jTextAreaNotas.setBackground(new java.awt.Color(51, 51, 51));
        jTextAreaNotas.setColumns(20);
        jTextAreaNotas.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jTextAreaNotas.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaNotas.setRows(5);
        jScrollPane1.setViewportView(jTextAreaNotas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 730, -1));

        jButtonAgregarTarea.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAgregarTarea.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButtonAgregarTarea.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregarTarea.setText("Agregar");
        jButtonAgregarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarTareaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 836, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
         //System.exit(0);
         dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAgregarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarTareaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonAgregarTareaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarTarea;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButtonAlta;
    private javax.swing.JRadioButton jRadioButtonBaja;
    private javax.swing.JRadioButton jRadioButtonMedia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaNotas;
    private javax.swing.JTextField jTextFieldFechaFin;
    private javax.swing.JTextField jTextFieldFechaInicio;
    private javax.swing.JTextField jTextFieldResponsable;
    private javax.swing.JTextField jTextFieldTarea;
    // End of variables declaration//GEN-END:variables
}
