/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author braul
 */
public class InterfazInicial extends javax.swing.JFrame {

    /**
     * Creates new form InterfazInicial
     */
    public InterfazInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAgregarTarea = new javax.swing.JButton();
        jButtonEditarUsuario = new javax.swing.JButton();
        jButtonEliminarTarea = new javax.swing.JButton();
        jButtonModificarTarea = new javax.swing.JButton();
        jButtonVerTarea = new javax.swing.JButton();
        jButtonAgregarUsuario = new javax.swing.JButton();
        jButtonEliminarUsuario = new javax.swing.JButton();
        jButtonVerUsuario = new javax.swing.JButton();
        jButtonGantt = new javax.swing.JButton();
        jButtonCerrarSes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAgregarTarea.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAgregarTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar_tareaV2.png"))); // NOI18N
        jButtonAgregarTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAgregarTareaMouseExited(evt);
            }
        });
        jButtonAgregarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarTareaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jButtonEditarUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jButtonEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar_usuario.png"))); // NOI18N
        jButtonEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jButtonEliminarTarea.setBackground(new java.awt.Color(51, 51, 51));
        jButtonEliminarTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar_tarea.png"))); // NOI18N
        jButtonEliminarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarTareaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jButtonModificarTarea.setBackground(new java.awt.Color(51, 51, 51));
        jButtonModificarTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar_tarea.png"))); // NOI18N
        jButtonModificarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarTareaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jButtonVerTarea.setBackground(new java.awt.Color(51, 51, 51));
        jButtonVerTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abrir_tarea.png"))); // NOI18N
        jButtonVerTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerTareaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        jButtonAgregarUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAgregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngegg.png"))); // NOI18N
        jButtonAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jButtonEliminarUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jButtonEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar_usuario.png"))); // NOI18N
        jButtonEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jButtonVerUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jButtonVerUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ver_usuario.png"))); // NOI18N
        jButtonVerUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        jButtonGantt.setBackground(new java.awt.Color(51, 51, 51));
        jButtonGantt.setForeground(new java.awt.Color(0, 0, 0));
        jButtonGantt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gantt.png"))); // NOI18N
        jButtonGantt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGanttActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGantt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jButtonCerrarSes.setBackground(new java.awt.Color(51, 51, 51));
        jButtonCerrarSes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar_ses.png"))); // NOI18N
        jButtonCerrarSes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrarSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -6, 730, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarTareaActionPerformed
        // TODO add your handling code here:
        InterfazTarea abrir = new InterfazTarea();
        abrir.setVisible(true);
    }//GEN-LAST:event_jButtonAgregarTareaActionPerformed

    private void jButtonEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarUsuarioActionPerformed
        // TODO add your handling code here:
        InterfazModificarUsuario abrir = new InterfazModificarUsuario();
        abrir.setVisible(true);
        String texto = "Modificar Usuario";
        jButtonAgregarTarea.setToolTipText(texto);
    }//GEN-LAST:event_jButtonEditarUsuarioActionPerformed

    private void jButtonAgregarTareaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarTareaMouseExited
        // TODO add your handling code here:
        String texto="Agregar tarea";
        jButtonAgregarTarea.setToolTipText(texto);
    }//GEN-LAST:event_jButtonAgregarTareaMouseExited

    private void jButtonModificarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarTareaActionPerformed
        // TODO add your handling code here:
        InterfazModificarTarea abrir = new InterfazModificarTarea();
        abrir.setVisible(true);
        String texto="Modificar tarea";
        jButtonAgregarTarea.setToolTipText(texto);
    }//GEN-LAST:event_jButtonModificarTareaActionPerformed

    private void jButtonEliminarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarTareaActionPerformed
        // TODO add your handling code here:
        InterfazEliminarTarea abrir = new InterfazEliminarTarea();
        abrir.setVisible(true);
        String texto="Eliminar tarea";
        jButtonAgregarTarea.setToolTipText(texto);
    }//GEN-LAST:event_jButtonEliminarTareaActionPerformed

    private void jButtonAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarUsuarioActionPerformed
        // TODO add your handling code here:
        InterfazAgregarUsuario abrir = new InterfazAgregarUsuario();
        abrir.setVisible(true);
        String txt = "Agregar Usuario";
        jButtonAgregarTarea.setToolTipText(txt);
    }//GEN-LAST:event_jButtonAgregarUsuarioActionPerformed

    private void jButtonVerTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerTareaActionPerformed
        // TODO add your handling code here:
        InterfazVerTarea abrir = new InterfazVerTarea();
        abrir.setVisible(true);
        String txt ="Ver tareas";
        jButtonVerTarea.setToolTipText(txt);
    }//GEN-LAST:event_jButtonVerTareaActionPerformed

    private void jButtonEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarUsuarioActionPerformed
        // TODO add your handling code here:
        InterfazEliminarUsuario abrir = new InterfazEliminarUsuario();
        abrir.setVisible(true);
        String txt = "Eliminar usuario";
        jButtonVerTarea.setToolTipText(txt);
    }//GEN-LAST:event_jButtonEliminarUsuarioActionPerformed

    private void jButtonVerUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerUsuarioActionPerformed
        // TODO add your handling code here:
        InterfazVerUsuarios abrir = new InterfazVerUsuarios();
        abrir.setVisible(true);
        String txt = "Ver Usuarios";
        jButtonVerTarea.setToolTipText(txt);
    }//GEN-LAST:event_jButtonVerUsuarioActionPerformed

    private void jButtonGanttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGanttActionPerformed
        // TODO add your handling code here:
        InterfazGrafica abrir = new InterfazGrafica();
        abrir.setVisible(true);
        String txt = "Gráfica de Gantt";
        jButtonVerTarea.setToolTipText(txt);
    }//GEN-LAST:event_jButtonGanttActionPerformed

    private void jButtonCerrarSesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesActionPerformed
        // TODO add your handling code here:
        dispose();
        InterfazLogin abrir = new InterfazLogin();
        abrir.setVisible(true);
    }//GEN-LAST:event_jButtonCerrarSesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarTarea;
    private javax.swing.JButton jButtonAgregarUsuario;
    private javax.swing.JButton jButtonCerrarSes;
    private javax.swing.JButton jButtonEditarUsuario;
    private javax.swing.JButton jButtonEliminarTarea;
    private javax.swing.JButton jButtonEliminarUsuario;
    private javax.swing.JButton jButtonGantt;
    private javax.swing.JButton jButtonModificarTarea;
    private javax.swing.JButton jButtonVerTarea;
    private javax.swing.JButton jButtonVerUsuario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
